name: armourers_workshop
version: '${version}'
main: moe.plushie.armourers_workshop.ArmourersWorkshopPlugin
api-version: 1.16
depend: [ cocoon ]
authors: [ SAGESSE, Happy_FZM ]
description: Armourer's Workshop Plugin