name: armourers_workshop
version: '${version}'
main: moe.plushie.armourers_workshop.ArmourersWorkshopImpl
api-version: 1.16
depend: [ ProtocolLib ]
authors: [ SAGESSE, Happy_FZM ]
description: Armourer's Workshop Plugin